name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags: ["*"]

jobs:
  lint:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - run: yarn install --immutable

      - name: Prettier
        run: |
          npx prettier --check .

      - name: eslint
        run: |
          npx eslint

  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - run: yarn install --immutable

      - name: Build
        run: |
          yarn build

      - name: Test
        run: |
          yarn test
